kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  config.json: |-
{{ .Files.Get (print "config-" .Values.envSuffix .Values.appSuffix ".json") | indent 4}}
