# Forward authentication to example.com
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-middleware
  namespace: {{ .Values.namespace }}
spec:
  forwardAuth:
    address: https://oauth2-middleware.{{ .Values.ingress.host.environment }}.kriegerit.de/authorize?redirectUri=https://{{ include "application.ingress.host" . }}
    authResponseHeaders:
      - authorization
